### ISSUE TITLE
Question about epoch

### ISSUE THREAD

**Issue by 1000jin** [XifengGuo/DEC-keras#13]
Thanks for your great implementation! 
I have a question doing experiment with it. There are default settings for epoch. (e.g. MNIST - 300 epochs) Are they the same value with your IDEC paper experiment?

I want to reproduce your experiment for study, but the accuracy score that I took a experiment with  your DEC implementation is not correct with accuracy in your paper(IDEC).

**Comment by XifengGuo** [comment]
@1000jin No, there are not the same. The implementation of IDEC is in https://github.com/XifengGuo/IDEC
However, this repository is a newer version which is tuned after IDEC published.

**Comment by 1000jin** [comment]
Thanks for reply :)
