### ISSUE TITLE
TypeError: add_weight() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by ogencoglu** [XifengGuo/DEC-keras#16]
I got the following error when running python DEC.py

Using TensorFlow backend.
Namespace(ae_weights=None, batch_size=256, dataset='mnist', maxiter=20000.0, pretrain_epochs=None, save_dir='results', tol=0.001, update_interval=None)
MNIST samples (70000, 784)
Traceback (most recent call last):
  File "DEC.py", line 321, in <module>
    dec = DEC(dims=[x.shape[-1], 500, 500, 2000, 10], n_clusters=n_clusters, init=init)
  File "DEC.py", line 138, in __init__
    clustering_layer = ClusteringLayer(self.n_clusters, name='clustering')(self.encoder.output)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "DEC.py", line 91, in build
    self.clusters = self.add_weight((self.n_clusters, input_dim), initializer='glorot_uniform', name='clusters')
TypeError: add_weight() got multiple values for argument 'name'

**Comment by lazzyCloud** [comment]
I met the same problem, and I think I solve it. 
line 91 in DEC.py
self.clusters = self.add_weight((self.n_clusters, input_dim), initializer='glorot_uniform', name='clusters')
change it to:
self.clusters = self.add_weight(**shape=**(self.n_clusters, input_dim), initializer='glorot_uniform', name='clusters')

Maybe it works for you, good luck

**Comment by erdiolmezogullari** [comment]
It worked for me, as well. @lazzyCloud

**Comment by VishalPrasadIITGn** [comment]
worked for me too.

**Comment by XifengGuo** [comment]
This problem is caused by the difference of keras versions. @lazzyCloud has given the solution. Thanks.

**Comment by dada410** [comment]
Worked for me as well. @lazzyCloud, thanks.

**Comment by mikechen66** [comment]
TypeError: add_weight() got multiple values for argument 'name'

I have checked the keras/frcnn code. It is related to FixedBatchNormalization.py. It has four places where name is placed. So it incurs the above-mentioned TypeError.  But it is difficult to use the lazzyCloud method to correct the error. It is also hard to use the function definition to avoid the error for the four add_weight method.  I take the original snippet of the application from the weblink for your refernece. 

### 1. TypeError
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-45ebd6753614> in <module>
     16 
     17 # define the base network (resnet here, can be VGG, Inception, etc)
---> 18 shared_layers = nn.nn_base(img_input, trainable=True)
     19 
     20 # define the RPN, built on the base layers

~/keras-frcnn/keras_frcnn/resnet.py in nn_base(input_tensor, trainable)
    190     # Do not correct "trainable = trainable" to "trainable=True"
    191     x = Convolution2D(64, (7, 7), strides=(2, 2), name='conv1', trainable=trainable)(x)
--> 192     x = FixedBatchNormalization(axis=bn_axis, name='bn_conv1')(x)
    193     x = Activation('relu')(x)
    194     x = MaxPooling2D((3, 3), strides=(2, 2))(x)

~/miniconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
     73         if _SYMBOLIC_SCOPE.value:
     74             with get_graph().as_default():
---> 75                 return func(*args, **kwargs)
     76         else:
     77             return func(*args, **kwargs)

~/miniconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    461                                          'You can build it manually via: '
    462                                          '`layer.build(batch_input_shape)`')
--> 463                 self.build(unpack_singleton(input_shapes))
    464                 self.built = True
    465 

~/keras-frcnn/keras_frcnn/FixedBatchNormalization.py in build(self, input_shape)
     28                                  regularizer=self.gamma_regularizer,
     29                                  name='{}_gamma'.format(self.name),
---> 30                                  trainable=False)
     31         self.beta = self.add_weight(shape=(input_shape[self.axis],),
     32                                 initializer=self.beta_init,

TypeError: add_weight() got multiple values for argument 'name'


### 2. Application: 

keras-frcnn:  https://github.com/kbardool/keras-frcnn/blob/master/keras_frcnn/FixedBatchNormalization.py
 

### 3. Snippet 

```
def build(self, input_shape):
    self.input_spec = [InputSpec(shape=input_shape)]
    shape = (input_shape[self.axis],)

    self.gamma = self.add_weight(shape,
                                 initializer=self.gamma_init,
                                 regularizer=self.gamma_regularizer,
                                 name='{}_gamma'.format(self.name),
                                 trainable=False)
    self.beta = self.add_weight(shape,
                                initializer=self.beta_init,
                                regularizer=self.beta_regularizer,
                                name='{}_beta'.format(self.name),
                                trainable=False)
    self.running_mean = self.add_weight(shape, initializer='zero',
                                        name='{}_running_mean'.format(self.name),
                                        trainable=False)
    self.running_std = self.add_weight(shape, initializer='one',
                                       name='{}_running_std'.format(self.name),
                                       trainable=False)

    if self.initial_weights is not None:
        self.set_weights(self.initial_weights)
        del self.initial_weights

    self.built = True
```
Hope to get feedback from you.

Mike

**Comment by HaowenGuan** [comment]
Worked for me, thanks

**Comment by iliastsergoulas** [comment]
I am having the same case as @mikechen66 mentions. Any workaround or solution for it?

**Comment by lakshmiwgl** [comment]
any solution on it @mikechen66.. I tried to implement the same code .. but getting errors you mentioned
