### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by dnnguifever** [XifengGuo/DEC-keras#6]
Hellos, this is great work. Thanks!

I just have a question, how can I use my own dataset with this? I have a folder of images that I would like clustered. 

Thanks!

**Comment by XifengGuo** [comment]
@dnnguifever You need to write a function to load your images to a numpy array with shape=[n, d], where n is the number of images and d is the dimension of each image. Please see datasets.py to understand the required format.

**Comment by dnnguifever** [comment]
HiSamy, could you take each day's data to be an image? So, 24 pixels (hours) in each image (day), arranged in some kind of matrix, 6x4, say, or 24x1?

**Comment by basque21** [comment]
I want to make clusters of texts of different topics, which are unlabelled. Say I have notices about sport, economy and politics, would it be possible to train the DeepCluster for making this 3 clusters without any labelled text? what would i need, train first in reuters dataset?
Thanks for your work!

**Comment by basque21** [comment]
I have trained the reuters dataset with DEC.py and runned the experiment with run_exp.py, but I don't know how I can introduce my non-labelled dataset to cluster it. Could you help me with this please?

**Comment by XifengGuo** [comment]
@basque21 The DEC itself is an unsupervised algorithm. So you can directly train DEC on your unlabeled data, just remember to remove the codes that require `y`. I recommend you try k-means first in order to understand how to cluster unlabeled data.
