### ISSUE TITLE
Is it possible to get less than the ground truth number of classes?

### ISSUE THREAD

**Issue by himanshisyadav** [XifengGuo/DEC-keras#8]
I am using the repo on [hyperspectral datasets](http://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes) and without changing any hyperparameters, I get around negative or very close to 0 ari values and the number of predicted classes is less than the ground truth number of classes.

Any suggestions? The pretraining itself is biased towards having a lesser number of clusters.

**Comment by XifengGuo** [comment]
@himanshisyadav First, DEC requires the ground truth number of clusters as one of the input parameters. So I don't understand "the number of predicted classes is less than the ground truth number of classes". 

Second, the objective of DEC is designed to cluster datasets with balanced clusters. The hyperspectral dataset is unbalanced (some class has many samples, some very few). So the clustering performance may be bad.

Third, I have noticed that DEC can not work well on many datasets. It proves that DEC has its own limitations. After all, we can not expect one model solves all problems.

**Comment by hammad97** [comment]
Well it may appear as number of predicted classes are less than ground truth when multiple cluster centroids maps on same location. Same things happen to me. That is again just DEC limitation.
