### ISSUE TITLE
Possible to get code working with plaidml backend?

### ISSUE THREAD

**Issue by karamheen** [XifengGuo/DEC-keras#9]
$ python DEC.py --dataset mnist
Using plaidml.keras.backend backend.
Namespace(ae_weights=None, batch_size=256, dataset='mnist', maxiter=20000.0, pretrain_epochs=None, save_dir='results', tol=0.001, update_interval=None)
('MNIST samples', (70000, 784))
INFO:plaidml:Opening device "metal_amd_radeon_hd_-_firepro_d500.1"
  return array(obj, copy=False)
Traceback (most recent call last):
  File "DEC.py", line 321, in <module>
    dec = DEC(dims=[x.shape[-1], 500, 500, 2000, 10], n_clusters=n_clusters, init=init)
  File "DEC.py", line 138, in __init__
    clustering_layer = ClusteringLayer(self.n_clusters, name='clustering')(self.encoder.output)
  File "/Users/test/plaidml-venv/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "DEC.py", line 106, in call
    q **= (self.alpha + 1.0) / 2.0
TypeError: unsupported operand type(s) for ** or pow(): 'Value' and 'float'

**Comment by XifengGuo** [comment]
@karamheen It should be able to work with plaidml backend, though I'm not familiar with the plaidml. The error is unsupported operand type, so you can try `q = K.pow(q, (self.alpha + 1.0) / 2.0)`. Continue to debug like this until it works.
